version: '3'

services: 
  oracle: 
    image: store/oracle/database-enterprise:12.2.0.1-slim
    container_name: oracle
    ports: 
      - 1521:1521
      - 5500:5500
    volumes: 
      - /home/diego/dockers/oracle/data:/opt/oracle/oradata