version: '2'

services:

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    volumes: 
      - /home/diego/projetos/dockers/mongodb/data/db:/data/db
    ports:
      - "27017:27017"